# EDA

In [1]:
import numpy as np
import pandas as pd
import mysql.connector
from IPython.display import display
import warnings
warnings.filterwarnings("ignore")

In [10]:
connection = mysql.connector.connect(
    host="localhost",
    user="root",
    password="suyog123poudel",
    database="company_db"
)
cursor = connection.cursor()

In [3]:
query = "show tables"
cursor.execute(query)
tables  = cursor.fetchall()

In [4]:
for table in tables:
    query = f"SELECT COUNT(*) from {table[0]}"
    cursor.execute(query)
    counts = cursor.fetchall()
    print(f"\n--------------------- {table[0]}--------------")
    print("Total rows ",counts[0][0])
    query = f"Select * from {table[0]} limit 5"
    display(pd.read_sql(query,connection))

--------------------- begin_inventory--------------
Total rows  206529

,InventoryId,Store,City,Brand,Description,Size,onHand,Price,startDate
0,1_HARDERSFIELD_58,1,HARDERSFIELD,58,Gekkeikan Black & Gold Sake,750mL,8,12.99,2024-01-01
1,1_HARDERSFIELD_60,1,HARDERSFIELD,60,Canadian Club 1858 VAP,750mL,7,10.99,2024-01-01
2,1_HARDERSFIELD_62,1,HARDERSFIELD,62,Herradura Silver Tequila,750mL,6,36.99,2024-01-01
3,1_HARDERSFIELD_63,1,HARDERSFIELD,63,Herradura Reposado Tequila,750mL,3,38.99,2024-01-01
4,1_HARDERSFIELD_72,1,HARDERSFIELD,72,No. 3 London Dry Gin,750mL,6,34.99,2024-01-01

--------------------- end_inventory--------------
Total rows  224489

,InventoryId,Store,City,Brand,Description,Size,onHand,Price,endDate
0,1_HARDERSFIELD_58,1,HARDERSFIELD,58,Gekkeikan Black & Gold Sake,750mL,11,12.99,2024-12-31
1,1_HARDERSFIELD_62,1,HARDERSFIELD,62,Herradura Silver Tequila,750mL,7,36.99,2024-12-31
2,1_HARDERSFIELD_63,1,HARDERSFIELD,63,Herradura Reposado Tequila,750mL,7,38.99,2024-12-31
3,1_HARDERSFIELD_72,1,HARDERSFIELD,72,No. 3 London Dry Gin,750mL,4,34.99,2024-12-31
4,1_HARDERSFIELD_75,1,HARDERSFIELD,75,Three Olives Tomato Vodka,750mL,7,14.99,2024-12-31

--------------------- purchase_prices--------------
Total rows  12261

,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName
0,58,Gekkeikan Black & Gold Sake,12.99,750mL,750,1,9.28,8320,SHAW ROSS INT L IMP LTD
1,62,Herradura Silver Tequila,36.99,750mL,750,1,28.67,1128,BROWN-FORMAN CORP
2,63,Herradura Reposado Tequila,38.99,750mL,750,1,30.46,1128,BROWN-FORMAN CORP
3,72,No. 3 London Dry Gin,34.99,750mL,750,1,26.11,9165,ULTRA BEVERAGE COMPANY LLP
4,75,Three Olives Tomato Vodka,14.99,750mL,750,1,10.94,7245,PROXIMO SPIRITS INC.

--------------------- purchases--------------
Total rows  2372474

,InventoryId,Store,Brand,Description,Size,VendorNumber,VendorName,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification
0,69_MOUNTMEND_8412,69,8412,Tequila Ocho Plata Fresno,750mL,105,ALTAMAR BRANDS LLC,8124,2023-12-21,2024-01-02,2024-01-04,2024-02-16,35.71,6,214.26,1
1,30_CULCHETH_5255,30,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,4,37.40,1
2,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-02,2024-01-07,2024-02-21,9.41,5,47.05,1
3,1_HARDERSFIELD_5255,1,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,6,56.10,1
4,76_DONCASTER_2034,76,2034,Glendalough Double Barrel,750mL,388,ATLANTIC IMPORTING COMPANY,8169,2023-12-24,2024-01-02,2024-01-09,2024-02-16,21.32,5,106.60,1

--------------------- sales--------------
Total rows  12825363

,InventoryId,Store,Brand,Description,Size,SalesQuantity,SalesDollars,SalesPrice,SalesDate,Volume,Classification,ExciseTax,VendorNo,VendorName
0,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,2024-01-01,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
1,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,2,32.98,16.49,2024-01-02,750.0,1,1.57,12546,JIM BEAM BRANDS COMPANY
2,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,2024-01-03,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
3,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,14.49,14.49,2024-01-08,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
4,1_HARDERSFIELD_1005,1,1005,Maker's Mark Combo Pack,375mL 2 Pk,2,69.98,34.99,2024-01-09,375.0,1,0.79,12546,JIM BEAM BRANDS COMPANY

--------------------- vendor_invoice--------------
Total rows  5543

,VendorNumber,VendorName,InvoiceDate,PONumber,PODate,PayDate,Quantity,Dollars,Freight,Approval
0,105,ALTAMAR BRANDS LLC,2024-01-04,8124,2023-12-21,2024-02-16,6,214.26,3.47,None
1,4466,AMERICAN VINTAGE BEVERAGE,2024-01-07,8137,2023-12-22,2024-02-21,15,140.55,8.57,None
2,388,ATLANTIC IMPORTING COMPANY,2024-01-09,8169,2023-12-24,2024-02-16,5,106.60,4.61,None
3,480,BACARDI USA INC,2024-01-12,8106,2023-12-20,2024-02-05,10100,137483.78,2935.20,None
4,516,BANFI PRODUCTS CORP,2024-01-07,8170,2023-12-24,2024-02-12,1935,15527.25,429.20,None

In [5]:
query = "Select * from purchase_prices where VendorNumber = 8320"
purchase_prices = pd.read_sql(query,connection)
display(purchase_prices.head())

,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName
0,58,Gekkeikan Black & Gold Sake,12.99,750mL,750,1,9.28,8320,SHAW ROSS INT L IMP LTD
1,2834,Old Smuggler P E T,15.99,1750mL,1750,1,12.30,8320,SHAW ROSS INT L IMP LTD
2,4412,Pusser's British Navy Rum,17.99,750mL,750,1,13.63,8320,SHAW ROSS INT L IMP LTD
3,7535,Gekkeikan Sake,5.99,750mL,750,1,4.44,8320,SHAW ROSS INT L IMP LTD
4,8346,Marques de Riscal Rioja Red,14.99,750mL,750,2,9.93,8320,SHAW ROSS INT L IMP LTD

In [6]:
query = "Select * from purchases where VendorNumber = 8320"
purchases = pd.read_sql(query,connection)
display(purchases.head())

,InventoryId,Store,Brand,Description,Size,VendorNumber,VendorName,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification
0,34_PITMERDEN_4412,34,4412,Pusser's British Navy Rum,750mL,8320,SHAW ROSS INT L IMP LTD,8166,2023-12-23,2024-01-02,2024-01-08,2024-02-11,13.63,6,81.78,1
1,76_DONCASTER_2834,76,2834,Old Smuggler P E T,1.75L,8320,SHAW ROSS INT L IMP LTD,8166,2023-12-23,2024-01-02,2024-01-08,2024-02-11,12.30,23,282.90,1
2,69_MOUNTMEND_29427,69,29427,Gekkeikan Sake Calif,18L,8320,SHAW ROSS INT L IMP LTD,8166,2023-12-23,2024-01-02,2024-01-08,2024-02-11,45.26,3,135.78,2
3,79_BALLYMENA_36558,79,36558,Cruz Garcia Real Sangria Re,1.5L,8320,SHAW ROSS INT L IMP LTD,8166,2023-12-23,2024-01-03,2024-01-08,2024-02-11,6.66,1,6.66,2
4,50_MOUNTMEND_8346,50,8346,Marques de Riscal Rioja Red,750mL,8320,SHAW ROSS INT L IMP LTD,8166,2023-12-23,2024-01-02,2024-01-08,2024-02-11,9.93,12,119.16,2

In [7]:
query = "Select * from sales where VendorNo = 8320"
sales = pd.read_sql(query,connection)
display(sales.head())

,InventoryId,Store,Brand,Description,Size,SalesQuantity,SalesDollars,SalesPrice,SalesDate,Volume,Classification,ExciseTax,VendorNo,VendorName
0,1_HARDERSFIELD_2834,1,2834,Old Smuggler P E T,1.75L,1,16.49,16.49,2024-01-03,1750.0,1,1.84,8320,SHAW ROSS INT L IMP LTD
1,1_HARDERSFIELD_2834,1,2834,Old Smuggler P E T,1.75L,1,16.49,16.49,2024-01-13,1750.0,1,1.84,8320,SHAW ROSS INT L IMP LTD
2,1_HARDERSFIELD_2834,1,2834,Old Smuggler P E T,1.75L,2,32.98,16.49,2024-01-17,1750.0,1,3.67,8320,SHAW ROSS INT L IMP LTD
3,1_HARDERSFIELD_2834,1,2834,Old Smuggler P E T,1.75L,1,16.49,16.49,2024-01-20,1750.0,1,1.84,8320,SHAW ROSS INT L IMP LTD
4,1_HARDERSFIELD_2834,1,2834,Old Smuggler P E T,1.75L,1,16.49,16.49,2024-01-21,1750.0,1,1.84,8320,SHAW ROSS INT L IMP LTD

In [8]:
query = "Select * from vendor_invoice where VendorNumber = 8320"
vendor_invoice = pd.read_sql(query,connection)
display(vendor_invoice)

,VendorNumber,VendorName,InvoiceDate,PONumber,PODate,PayDate,Quantity,Dollars,Freight,Approval
0,8320,SHAW ROSS INT L IMP LTD,2024-01-08,8166,2023-12-23,2024-02-11,279,2392.18,51.37,None
1,8320,SHAW ROSS INT L IMP LTD,2024-01-19,8246,2023-12-29,2024-02-21,895,7987.83,43.93,None
2,8320,SHAW ROSS INT L IMP LTD,2024-01-20,8367,2024-01-06,2024-02-21,1134,9112.05,47.38,None
3,8320,SHAW ROSS INT L IMP LTD,2024-01-28,8493,2024-01-15,2024-03-05,1108,9847.50,48.25,None
4,8320,SHAW ROSS INT L IMP LTD,2024-02-04,8530,2024-01-18,2024-03-04,1228,9950.29,47.76,None
5,8320,SHAW ROSS INT L IMP LTD,2024-02-16,8666,2024-01-27,2024-03-21,1105,9357.95,48.66,None
6,8320,SHAW ROSS INT L IMP LTD,2024-02-20,8772,2024-02-03,2024-03-29,1175,9654.85,44.41,None
7,8320,SHAW ROSS INT L IMP LTD,2024-02-27,8835,2024-02-08,2024-03-31,1193,9696.74,45.57,None
8,8320,SHAW ROSS INT L IMP LTD,2024-03-01,8920,2024-02-14,2024-04-15,1213,9820.62,45.17,None
9,8320,SHAW ROSS INT L IMP LTD,2024-03-10,9108,2024-02-26,2024-04-14,1048,9030.46,49.67,None
10,8320,SHAW ROSS INT L IMP LTD,2024-03-15,9174,2024-03-02,2024-05-01,1021,8457.72,38.06,None
11,8320,SHAW ROSS INT L IMP LTD,2024-03-25,9270,2024-03-09,2024-05-04,956,7928.70,40.44,None
12,8320,SHAW ROSS INT L IMP LTD,2024-04-04,9353,2024-03-15,2024-04-30,977,8083.94,37.99,None
13,8320,SHAW ROSS INT L IMP LTD,2024-04-09,9428,2024-03-20,2024-05-06,947,8738.89,46.32,None
14,8320,SHAW ROSS INT L IMP LTD,2024-04-19,9556,2024-03-29,2024-05-13,1032,8443.89,39.69,None
15,8320,SHAW ROSS INT L IMP LTD,2024-04-24,9649,2024-04-04,2024-06-03,942,7996.59,43.18,None
16,8320,SHAW ROSS INT L IMP LTD,2024-05-03,9757,2024-04-12,2024-05-28,1124,10247.07,50.21,None
17,8320,SHAW ROSS INT L IMP LTD,2024-05-09,9827,2024-04-17,2024-06-10,1180,9991.70,53.96,None
18,8320,SHAW ROSS INT L IMP LTD,2024-05-12,10017,2024-04-29,2024-06-11,1286,10683.29,55.55,None
19,8320,SHAW ROSS INT L IMP LTD,2024-05-17,10090,2024-05-05,2024-07-03,870,8313.04,39.90,None
20,8320,SHAW ROSS INT L IMP LTD,2024-05-25,10196,2024-05-12,2024-06-29,1282,11350.79,62.43,None
21,8320,SHAW ROSS INT L IMP LTD,2024-05-30,10234,2024-05-15,2024-07-01,1296,11239.88,52.83,None
22,8320,SHAW ROSS INT L IMP LTD,2024-06-10,10357,2024-05-23,2024-07-10,1321,12116.28,54.52,None
23,8320,SHAW ROSS INT L IMP LTD,2024-06-15,10457,2024-05-30,2024-07-19,1372,12791.73,69.08,None
24,8320,SHAW ROSS INT L IMP LTD,2024-06-21,10626,2024-06-10,2024-07-28,1257,10415.75,52.08,None
25,8320,SHAW ROSS INT L IMP LTD,2024-07-02,10709,2024-06-16,2024-08-10,1579,13007.52,67.64,None
26,8320,SHAW ROSS INT L IMP LTD,2024-07-04,10791,2024-06-22,2024-08-09,1201,11167.55,56.95,None
27,8320,SHAW ROSS INT L IMP LTD,2024-07-06,10898,2024-06-25,2024-08-14,387,4207.65,19.36,None
28,8320,SHAW ROSS INT L IMP LTD,2024-07-17,10930,2024-06-26,2024-08-13,1923,18589.14,91.09,None
29,8320,SHAW ROSS INT L IMP LTD,2024-07-25,11090,2024-07-06,2024-08-18,1172,10420.53,48.98,None
30,8320,SHAW ROSS INT L IMP LTD,2024-07-29,11149,2024-07-11,2024-09-07,1537,13651.94,66.89,None
31,8320,SHAW ROSS INT L IMP LTD,2024-08-01,11292,2024-07-20,2024-09-12,1265,12146.51,61.95,None
32,8320,SHAW ROSS INT L IMP LTD,2024-08-15,11336,2024-07-24,2024-09-19,1996,18659.38,98.89,None
33,8320,SHAW ROSS INT L IMP LTD,2024-08-23,11501,2024-08-04,2024-09-26,1697,16194.76,84.21,None
34,8320,SHAW ROSS INT L IMP LTD,2024-08-25,11618,2024-08-11,2024-10-03,2322,20502.92,110.72,None
35,8320,SHAW ROSS INT L IMP LTD,2024-09-01,11698,2024-08-17,2024-10-08,1473,12966.02,58.35,None
36,8320,SHAW ROSS INT L IMP LTD,2024-09-08,11815,2024-08-25,2024-10-09,1510,15023.23,72.11,None
37,8320,SHAW ROSS INT L IMP LTD,2024-09-20,11895,2024-08-31,2024-10-25,1466,13599.55,61.20,None
38,8320,SHAW ROSS INT L IMP LTD,2024-09-22,11985,2024-09-06,2024-10-28,1374,12553.35,66.53,None
39,8320,SHAW ROSS INT L IMP LTD,2024-10-02,12072,2024-09-12,2024-11-12,1269,12902.18,64.51,None
40,8320,SHAW ROSS INT L IMP LTD,2024-10-11,12161,2024-09-18,2024-11-13,1602,20199.17,101.00,None
41,8320,SHAW ROSS INT L IMP LTD,2024-10-09,12292,2024-09-23,2024-11-07,82,1221.96,6.23,None
42,8320,SHAW ROSS INT L IMP LTD,2024-10-15,12353,2024-09-27,2024-11-23,1150,9962.24,52.80,None
43,8320,SHAW ROSS INT L IMP LTD,2024-10-19,12444,2024-10-03,2024-11-22,1538,14216.19,66.82,None
44,8320,SHAW ROSS INT L IMP LTD,2024-10-29,12530,2024-10-09,2024-12-11,1645,15475.42,74.28,None
45,8320,SHAW ROSS INT L IMP LTD,2024-11-02,12628,2024-10-16,2024-12-01,1369,12627.62,63.14,None
46,8320,SHAW ROSS INT L IMP LTD,2024-11-12,12784,2024-10-26,2024-12-12,1229,10864.56,52.15,None
47,8320,SHAW ROSS INT L IMP LTD,2024-11-20,12864,2024-10-31,2024-12-29,1446,12992.81,66.26,None
48,8320,SHAW ROSS INT L IMP LTD,2024-11-27,13010,2024-11-10,2024-12-23,1287,11223.64,58.36,None
49,8320,SHAW ROSS INT L IMP LTD,2024-12-06,13045,2024-11-13,2025-01-04,1238,11288.24,57.57,None
50,8320,SHAW ROSS INT L IMP LTD,2024-12-06,13166,2024-11-21,2025-01-05,1611,14704.84,73.52,None
51,8320,SHAW ROSS INT L IMP LTD,2024-12-20,13266,2024-11-28,2025-01-27,1249,11473.10,52.78,None
52,8320,SHAW ROSS INT L IMP LTD,2024-12-26,13366,2024-12-05,2025-02-02,1391,12603.43,65.54,None
53,8320,SHAW ROSS INT L IMP LTD,2024-12-27,13508,2024-12-14,2025-01-30,1441,13501.92,63.46,None
54,8320,SHAW ROSS INT L IMP LTD,2025-01-09,13568,2024-12-18,2025-02-13,1437,13382.54,60.22,None

In [9]:
purchases[purchases["PONumber"] == 8166]

,InventoryId,Store,Brand,Description,Size,VendorNumber,VendorName,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification
0,34_PITMERDEN_4412,34,4412,Pusser's British Navy Rum,750mL,8320,SHAW ROSS INT L IMP LTD,8166,2023-12-23,2024-01-02,2024-01-08,2024-02-11,13.63,6,81.78,1
1,76_DONCASTER_2834,76,2834,Old Smuggler P E T,1.75L,8320,SHAW ROSS INT L IMP LTD,8166,2023-12-23,2024-01-02,2024-01-08,2024-02-11,12.30,23,282.90,1
2,69_MOUNTMEND_29427,69,29427,Gekkeikan Sake Calif,18L,8320,SHAW ROSS INT L IMP LTD,8166,2023-12-23,2024-01-02,2024-01-08,2024-02-11,45.26,3,135.78,2
3,79_BALLYMENA_36558,79,36558,Cruz Garcia Real Sangria Re,1.5L,8320,SHAW ROSS INT L IMP LTD,8166,2023-12-23,2024-01-03,2024-01-08,2024-02-11,6.66,1,6.66,2
4,50_MOUNTMEND_8346,50,8346,Marques de Riscal Rioja Red,750mL,8320,SHAW ROSS INT L IMP LTD,8166,2023-12-23,2024-01-02,2024-01-08,2024-02-11,9.93,12,119.16,2
5,1_HARDERSFIELD_58,1,58,Gekkeikan Black & Gold Sake,750mL,8320,SHAW ROSS INT L IMP LTD,8166,2023-12-23,2024-01-01,2024-01-08,2024-02-11,9.28,6,55.68,1
6,69_MOUNTMEND_8696,69,8696,Gekkeikan Plum Wine,750mL,8320,SHAW ROSS INT L IMP LTD,8166,2023-12-23,2024-01-02,2024-01-08,2024-02-11,7.48,8,59.84,2
7,37_PAETHSMOUTH_36558,37,36558,Cruz Garcia Real Sangria Re,1.5L,8320,SHAW ROSS INT L IMP LTD,8166,2023-12-23,2024-01-02,2024-01-08,2024-02-11,6.66,6,39.96,2
8,7_STANMORE_8346,7,8346,Marques de Riscal Rioja Red,750mL,8320,SHAW ROSS INT L IMP LTD,8166,2023-12-23,2024-01-02,2024-01-08,2024-02-11,9.93,12,119.16,2
9,78_EASTHAVEN_2834,78,2834,Old Smuggler P E T,1.75L,8320,SHAW ROSS INT L IMP LTD,8166,2023-12-23,2024-01-01,2024-01-08,2024-02-11,12.30,6,73.80,1
10,50_MOUNTMEND_58,50,58,Gekkeikan Black & Gold Sake,750mL,8320,SHAW ROSS INT L IMP LTD,8166,2023-12-23,2024-01-02,2024-01-08,2024-02-11,9.28,5,46.40,1
11,15_WANBORNE_2834,15,2834,Old Smuggler P E T,1.75L,8320,SHAW ROSS INT L IMP LTD,8166,2023-12-23,2024-01-01,2024-01-08,2024-02-11,12.30,5,61.50,1
12,76_DONCASTER_7535,76,7535,Gekkeikan Sake,750mL,8320,SHAW ROSS INT L IMP LTD,8166,2023-12-23,2024-01-02,2024-01-08,2024-02-11,4.44,12,53.28,1
13,69_MOUNTMEND_2834,69,2834,Old Smuggler P E T,1.75L,8320,SHAW ROSS INT L IMP LTD,8166,2023-12-23,2024-01-02,2024-01-08,2024-02-11,12.30,6,73.80,1
14,38_GOULCREST_43124,38,43124,Gekkeikan Nigori Sake,300mL,8320,SHAW ROSS INT L IMP LTD,8166,2023-12-23,2024-01-01,2024-01-08,2024-02-11,4.10,12,49.20,2
15,1_HARDERSFIELD_8346,1,8346,Marques de Riscal Rioja Red,750mL,8320,SHAW ROSS INT L IMP LTD,8166,2023-12-23,2024-01-01,2024-01-08,2024-02-11,9.93,12,119.16,2
16,47_PELLA'S WISH_7535,47,7535,Gekkeikan Sake,750mL,8320,SHAW ROSS INT L IMP LTD,8166,2023-12-23,2024-01-02,2024-01-08,2024-02-11,4.44,12,53.28,1
17,50_MOUNTMEND_7535,50,7535,Gekkeikan Sake,750mL,8320,SHAW ROSS INT L IMP LTD,8166,2023-12-23,2024-01-02,2024-01-08,2024-02-11,4.44,9,39.96,1
18,67_EANVERNESS_7535,67,7535,Gekkeikan Sake,750mL,8320,SHAW ROSS INT L IMP LTD,8166,2023-12-23,2024-01-02,2024-01-08,2024-02-11,4.44,11,48.84,1
19,29_AYLESBURY_8346,29,8346,Marques de Riscal Rioja Red,750mL,8320,SHAW ROSS INT L IMP LTD,8166,2023-12-23,2024-01-02,2024-01-08,2024-02-11,9.93,12,119.16,2
20,37_PAETHSMOUTH_8346,37,8346,Marques de Riscal Rioja Red,750mL,8320,SHAW ROSS INT L IMP LTD,8166,2023-12-23,2024-01-02,2024-01-08,2024-02-11,9.93,12,119.16,2
21,1_HARDERSFIELD_2834,1,2834,Old Smuggler P E T,1.75L,8320,SHAW ROSS INT L IMP LTD,8166,2023-12-23,2024-01-01,2024-01-08,2024-02-11,12.30,6,73.80,1
22,18_FURNESS_36558,18,36558,Cruz Garcia Real Sangria Re,1.5L,8320,SHAW ROSS INT L IMP LTD,8166,2023-12-23,2024-01-02,2024-01-08,2024-02-11,6.66,6,39.96,2
23,47_PELLA'S WISH_2834,47,2834,Old Smuggler P E T,1.75L,8320,SHAW ROSS INT L IMP LTD,8166,2023-12-23,2024-01-02,2024-01-08,2024-02-11,12.30,6,73.80,1
24,50_MOUNTMEND_2834,50,2834,Old Smuggler P E T,1.75L,8320,SHAW ROSS INT L IMP LTD,8166,2023-12-23,2024-01-02,2024-01-08,2024-02-11,12.30,4,49.20,1
25,30_CULCHETH_2834,30,2834,Old Smuggler P E T,1.75L,8320,SHAW ROSS INT L IMP LTD,8166,2023-12-23,2024-01-01,2024-01-08,2024-02-11,12.30,6,73.80,1
26,76_DONCASTER_44761,76,44761,Gekkeikan Sake Zipang Spklg,250mL,8320,SHAW ROSS INT L IMP LTD,8166,2023-12-23,2024-01-02,2024-01-08,2024-02-11,3.68,12,44.16,2
27,38_GOULCREST_7535,38,7535,Gekkeikan Sake,750mL,8320,SHAW ROSS INT L IMP LTD,8166,2023-12-23,2024-01-01,2024-01-08,2024-02-11,4.44,24,106.56,1
28,69_MOUNTMEND_8346,69,8346,Marques de Riscal Rioja Red,750mL,8320,SHAW ROSS INT L IMP LTD,8166,2023-12-23,2024-01-02,2024-01-08,2024-02-11,9.93,12,119.16,2
29,15_WANBORNE_7535,15,7535,Gekkeikan Sake,750mL,8320,SHAW ROSS INT L IMP LTD,8166,2023-12-23,2024-01-01,2024-01-08,2024-02-11,4.44,12,53.28,1

# PurchasePrice stores product cost details, while Purchases stores actual purchase transactions including quantity, dates, and total spend.

# Purchases vs Vendor Invoice

## The Purchases table contains item-level transaction details for each Purchase Order (PONumber), showing individual products, quantities, and prices, while the Vendor Invoice table aggregates these transactions at the vendor and order level, summarizing total quantity, total dollars, and freight per purchase order or billing cycle.



# Sales

# The Sales table stores transaction-level sales data, capturing each product sold at store level along with quantity, selling price, total sales value, tax, and vendor details.

# As the data that we need to analysis are in different table we need to create a summary table
- Purchase Transactions made by vendors
- sales transaction data
- freight cost for each vendor
- actual product price from vendor

In [21]:
query = """select p.VendorName,p.VendorNumber,p.Brand,p.PurchasePrice,pp.Price ActualPrice,pp.Volume,
sum(p.Quantity) TotalPurchaseQuantity , sum(p.Dollars) TotalPurchaseDollars
 from purchases p
join purchase_prices pp using(Brand)
where p.PurchasePrice >0
GROUP BY p.VendorName , p.VendorNumber,p.Brand,p.PurchasePrice,pp.Price,pp.Volume
order by p.VendorNumber asc"""

pd.read_sql_query(query,connection)

,VendorName,VendorNumber,Brand,PurchasePrice,ActualPrice,Volume,TotalPurchaseQuantity,TotalPurchaseDollars
0,"IRA GOLDMAN AND WILLIAMS, LLP",2,90085,23.86,36.99,750,8.0,190.88
1,"IRA GOLDMAN AND WILLIAMS, LLP",2,90609,17.00,24.99,162.5,320.0,5440.00
2,AAPER ALCOHOL & CHEMICAL CO,54,990,105.07,134.49,3750,1.0,105.07
3,ADAMBA IMPORTS INTL INC,60,3401,11.10,14.99,1750,6.0,66.60
4,ADAMBA IMPORTS INTL INC,60,3979,16.27,20.99,1750,4687.0,76257.49
...,...,...,...,...,...,...,...,...
10687,TAMWORTH DISTILLING,173357,2804,32.14,44.99,750,210.0,6749.40
10688,TAMWORTH DISTILLING,173357,3848,23.30,30.99,750,28.0,652.40
10689,TAMWORTH DISTILLING,173357,3909,19.37,24.99,750,1232.0,23863.84
10690,TAMWORTH DISTILLING,173357,3666,18.79,24.99,375,520.0,9770.80
10691,FLAVOR ESSENCE INC,201359,90609,17.00,24.99,162.5,1.0,17.00

In [24]:
query  = """select VendorNumber,VendorName,round( sum(Dollars),2) Cost, round(sum(Freight),2) Freight , sum(Quantity) Quantity from vendor_invoice
group by VendorNumber,VendorName
;"""
pd.read_sql_query(query,connection)

,VendorNumber,VendorName,Cost,Freight,Quantity
0,105,ALTAMAR BRANDS LLC,11706.20,62.39,332.0
1,4466,AMERICAN VINTAGE BEVERAGE,156357.28,793.91,15778.0
2,388,ATLANTIC IMPORTING COMPANY,41116.32,211.74,1847.0
3,480,BACARDI USA INC,17624378.72,89286.27,1427075.0
4,516,BANFI PRODUCTS CORP,1628866.68,8510.41,228103.0
...,...,...,...,...,...
124,4901,LAUREATE IMPORTS CO,140.94,0.72,29.0
125,90059,BLACK COVE BEVERAGES,14465.06,74.84,919.0
126,5083,LOYAL DOG WINERY,2320.80,10.68,240.0
127,1587,VINEYARD BRANDS LLC,10951.51,54.23,371.0
128,54,AAPER ALCOHOL & CHEMICAL CO,105.07,0.48,1.0

In [28]:
query = """select s.VendorNo,s.Brand,sum(SalesQuantity) SoldQuantity , round(sum(SalesDollars),2) TotalSalesDollars,
round(sum(SalesPrice),2) TotalSalesPrice , round(sum(s.ExciseTax),2) TotalExciseTax
from sales s group by s.VendorNo,s.VendorName,s.Brand
order by TotalSalesDollars;"""
pd.read_sql_query(query,connection)

,VendorNo,Brand,SoldQuantity,TotalSalesDollars,TotalSalesPrice,TotalExciseTax
0,8004,5287,2.0,0.98,0.98,0.10
1,9206,2773,1.0,0.99,0.99,0.05
2,3924,9123,2.0,1.98,0.99,0.10
3,3252,3933,2.0,1.98,0.99,0.10
4,10050,3623,2.0,1.98,1.98,0.10
...,...,...,...,...,...,...
11267,3960,3545,135838.0,4223107.62,545778.28,249587.83
11268,3960,4261,200412.0,4475972.88,420050.01,368242.80
11269,17035,8068,187140.0,4538120.60,461140.15,343854.07
11270,4425,3405,160247.0,4819073.49,561512.37,294438.66
11271,1128,1233,142049.0,5101919.51,672819.31,260999.20

In [74]:
connection = mysql.connector.connect(
    host="localhost",
    user="root",
    password="suyog123poudel",
    database="company_db"
)
cursor = connection.cursor()

In [13]:
query = """WITH PurchasePriceSummary AS (
    SELECT
        p.VendorNumber,
        p.VendorName,
        p.Brand,
        p.PurchasePrice,
        pp.Price AS ActualPrice,
        pp.Volume,
        p.Description,
        SUM(p.Quantity) AS TotalPurchaseQuantity,
        ROUND(SUM(p.Dollars),2) AS TotalPurchaseDollar
    FROM purchases p
    JOIN purchase_prices pp USING (Brand)
    GROUP BY
        p.VendorNumber,
        p.VendorName,
        p.Brand,
        pp.Price,
        p.PurchasePrice,
        pp.Volume,
        p.Description
),

VendorInvoiceSummary AS (
    SELECT
        vi.VendorNumber,
        SUM(vi.Freight) AS TotalFreight
    FROM vendor_invoice vi
    GROUP BY vi.VendorNumber
),

SalesSummary AS (
    SELECT
        s.VendorNo,
        s.Brand,
        s.VendorName,
        SUM(s.SalesQuantity) AS TotalSalesQuantity,
        ROUND(SUM(s.SalesDollars),2) AS TotalSalesDollars,
        ROUND(SUM(s.SalesPrice),2) AS TotalSalesPrice,
        ROUND(SUM(s.ExciseTax)) AS ExciseTax
    FROM sales s
    GROUP BY
        s.VendorNo,
        s.VendorName,
        s.Brand
)

SELECT
    pps.VendorNumber,
    pps.VendorName,
    pps.Brand,
    pps.Volume,
    pps.Description,
    pps.ActualPrice,
    pps.PurchasePrice,
    pps.TotalPurchaseQuantity,
    pps.TotalPurchaseDollar,

    ss.TotalSalesQuantity,
    ss.TotalSalesDollars,
    ss.TotalSalesPrice,
    ss.ExciseTax,

    vis.TotalFreight

FROM PurchasePriceSummary pps

LEFT JOIN SalesSummary ss
    ON pps.VendorNumber = ss.VendorNo
   AND pps.Brand = ss.Brand

LEFT JOIN VendorInvoiceSummary vis
    ON pps.VendorNumber = vis.VendorNumber;
"""

vendor_sales_summay = pd.read_sql_query(query,connection)

In [14]:
vendor_sales_summay

,VendorNumber,VendorName,Brand,Volume,Description,ActualPrice,PurchasePrice,TotalPurchaseQuantity,TotalPurchaseDollar,TotalSalesQuantity,TotalSalesDollars,TotalSalesPrice,ExciseTax,TotalFreight
0,105,ALTAMAR BRANDS LLC,8412,750,Tequila Ocho Plata Fresno,49.99,35.71,320.0,11427.20,307.0,15346.93,12947.41,242.0,62.39
1,4466,AMERICAN VINTAGE BEVERAGE,5255,1750,TGI Fridays Ultimte Mudslide,12.99,9.35,6215.0,58110.25,6096.0,79187.04,51180.60,11204.0,793.91
2,4466,AMERICAN VINTAGE BEVERAGE,5215,1750,TGI Fridays Long Island Iced,12.99,9.41,4923.0,46325.43,4651.0,60416.49,41542.02,8549.0,793.91
3,480,BACARDI USA INC,3348,1750,Bombay Sapphire Gin,29.99,22.38,57349.0,1283470.62,56888.0,1766391.12,460087.95,104525.0,89286.27
4,480,BACARDI USA INC,8358,750,Bacardi 151 Proof,19.99,14.49,7071.0,102458.79,8065.0,161219.35,87396.28,6353.0,89286.27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10688,4425,MARTIGNETTI COMPANIES,28007,750,Priest Ranch Sauvignon Blanc,18.99,12.41,120.0,1489.20,NaN,NaN,NaN,NaN,144929.24
10689,7153,PINE STATE TRADING CO,26508,750,Ch Maycott Red,10.49,6.81,1.0,6.81,1.0,10.49,10.49,0.0,15884.82
10690,8004,SAZERAC CO INC,2936,750,Abraham Bowman Ltd Edition,69.99,53.02,18.0,954.36,4.0,279.96,69.99,3.0,50293.62
10691,2000,SOUTHERN WINE & SPIRITS NE,26266,750,The Divining Rod Pinot Noir,16.99,11.56,132.0,1525.92,2.0,33.98,16.99,0.0,19016.59
10692,9165,ULTRA BEVERAGE COMPANY LLP,1073,750,Straw Boys Poitin,34.99,25.73,168.0,4322.64,NaN,NaN,NaN,NaN,68054.70

In [15]:
vendor_sales_summay.isnull().sum()

VendorNumber               0
VendorName                 0
Brand                      0
Volume                     0
Description                0
ActualPrice                0
PurchasePrice              0
TotalPurchaseQuantity      0
TotalPurchaseDollar        0
TotalSalesQuantity       178
TotalSalesDollars        178
TotalSalesPrice          178
ExciseTax                178
TotalFreight               0
dtype: int64

In [16]:
vendor_sales_summay.info()

<class 'pandas.DataFrame'>
RangeIndex: 10693 entries, 0 to 10692
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   VendorNumber           10693 non-null  int64
 1   VendorName             10693 non-null  str
 2   Brand                  10693 non-null  int64
 3   Volume                 10693 non-null  str
 4   Description            10693 non-null  str
 5   ActualPrice            10693 non-null  float64
 6   PurchasePrice          10693 non-null  float64
 7   TotalPurchaseQuantity  10693 non-null  float64
 8   TotalPurchaseDollar    10693 non-null  float64
 9   TotalSalesQuantity     10515 non-null  float64
 10  TotalSalesDollars      10515 non-null  float64
 11  TotalSalesPrice        10515 non-null  float64
 12  ExciseTax              10515 non-null  float64
 13  TotalFreight           10693 non-null  float64
dtypes: float64(9), int64(2), str(3)
memory usage: 1.7 MB

In [50]:
vendor_sales_summay_copy = vendor_sales_summay.copy()

In [52]:
vendor_sales_summay_copy.fillna(0,inplace=True)

,VendorNumber,VendorName,Brand,Volume,Description,ActualPrice,PurchasePrice,TotalPurchaseQuantity,TotalPurchaseDollar,TotalSalesQuantity,TotalSalesDollars,TotalSalesPrice,ExciseTax,TotalFreight
0,105,ALTAMAR BRANDS LLC,8412,750,Tequila Ocho Plata Fresno,49.99,35.71,320,11427.20,307.0,15346.93,12947.41,242.0,62.39
1,4466,AMERICAN VINTAGE BEVERAGE,5255,1750,TGI Fridays Ultimte Mudslide,12.99,9.35,6215,58110.25,6096.0,79187.04,51180.60,11204.0,793.91
2,4466,AMERICAN VINTAGE BEVERAGE,5215,1750,TGI Fridays Long Island Iced,12.99,9.41,4923,46325.43,4651.0,60416.49,41542.02,8549.0,793.91
3,480,BACARDI USA INC,3348,1750,Bombay Sapphire Gin,29.99,22.38,57349,1283470.62,56888.0,1766391.12,460087.95,104525.0,89286.27
4,480,BACARDI USA INC,8358,750,Bacardi 151 Proof,19.99,14.49,7071,102458.79,8065.0,161219.35,87396.28,6353.0,89286.27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10688,4425,MARTIGNETTI COMPANIES,28007,750,Priest Ranch Sauvignon Blanc,18.99,12.41,120,1489.20,0.0,0.00,0.00,0.0,144929.24
10689,7153,PINE STATE TRADING CO,26508,750,Ch Maycott Red,10.49,6.81,1,6.81,1.0,10.49,10.49,0.0,15884.82
10690,8004,SAZERAC CO INC,2936,750,Abraham Bowman Ltd Edition,69.99,53.02,18,954.36,4.0,279.96,69.99,3.0,50293.62
10691,2000,SOUTHERN WINE & SPIRITS NE,26266,750,The Divining Rod Pinot Noir,16.99,11.56,132,1525.92,2.0,33.98,16.99,0.0,19016.59
10692,9165,ULTRA BEVERAGE COMPANY LLP,1073,750,Straw Boys Poitin,34.99,25.73,168,4322.64,0.0,0.00,0.00,0.0,68054.70

In [53]:
def change_dtype(col_name,d_type):
    vendor_sales_summay_copy[col_name] = (vendor_sales_summay_copy[col_name]).astype(d_type)

In [54]:
for col,d_type in zip(["Volume","Volume","TotalPurchaseQuantity","TotalSalesQuantity"],["float","int","int","int"]):
    change_dtype(col,d_type)

In [57]:
vendor_sales_summay_copy.info()

<class 'pandas.DataFrame'>
RangeIndex: 10693 entries, 0 to 10692
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   VendorNumber           10693 non-null  int64
 1   VendorName             10693 non-null  str
 2   Brand                  10693 non-null  int64
 3   Volume                 10693 non-null  int64
 4   Description            10693 non-null  str
 5   ActualPrice            10693 non-null  float64
 6   PurchasePrice          10693 non-null  float64
 7   TotalPurchaseQuantity  10693 non-null  int64
 8   TotalPurchaseDollar    10693 non-null  float64
 9   TotalSalesQuantity     10693 non-null  int64
 10  TotalSalesDollars      10693 non-null  float64
 11  TotalSalesPrice        10693 non-null  float64
 12  ExciseTax              10693 non-null  float64
 13  TotalFreight           10693 non-null  float64
dtypes: float64(7), int64(5), str(2)
memory usage: 1.6 MB

In [58]:
def strip_data(col_name):
    vendor_sales_summay_copy[col_name] = vendor_sales_summay_copy[col_name].str.strip()

In [59]:
for col in ["VendorName","Description"]:
    strip_data(col)

In [62]:
vendor_sales_summay_copy["GrossProfit"] = vendor_sales_summay_copy["TotalSalesDollars"] - vendor_sales_summay_copy["TotalPurchaseDollar"]

In [63]:
vendor_sales_summay_copy["ProfitMargin"] = (vendor_sales_summay_copy["GrossProfit"] / vendor_sales_summay_copy["TotalSalesDollars"])*100

In [65]:
vendor_sales_summay_copy["StockTurnover"] = vendor_sales_summay_copy["TotalSalesQuantity"] / vendor_sales_summay_copy["TotalPurchaseQuantity"]

In [66]:
vendor_sales_summay_copy["SalesToPurchaseRatio"] = vendor_sales_summay_copy["TotalSalesDollars"] / vendor_sales_summay_copy["TotalPurchaseDollar"]

In [67]:
vendor_sales_summay_copy.columns

Index(['VendorNumber', 'VendorName', 'Brand', 'Volume', 'Description',
       'ActualPrice', 'PurchasePrice', 'TotalPurchaseQuantity',
       'TotalPurchaseDollar', 'TotalSalesQuantity', 'TotalSalesDollars',
       'TotalSalesPrice', 'ExciseTax', 'TotalFreight', 'GrossProfit',
       'ProfitMargin', 'StockTurnover', 'SalesToPurchaseRatio'],
      dtype='str')

In [100]:
vendor_sales_summay_copy = vendor_sales_summay_copy.replace([np.inf,-np.inf],np.nan)

In [102]:
vendor_sales_summay_copy = vendor_sales_summay_copy.fillna(0)

In [96]:
from sqlalchemy import create_engine

engine = create_engine("mysql+pymysql://root:suyog123poudel@localhost/company_db")

In [103]:
vendor_sales_summay_copy.to_sql(
    "vendor_sales_summary",
    con=engine,
    if_exists="append",
    index=False
)

10693